[project]
name = "artdeepresearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite",
    "apify",
    "beautifulsoup4",
    "crewai",
    "duckduckgo-search",
    "helium",
    "pillow",
    "python-dotenv",
    "requests",
    "ruff",
    "selenium",
    "smolagents[toolkit]",
    "sqlalchemy",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
testpaths = [
    "tests",
]
asyncio_mode = "auto"
